### ISSUE TITLE
Manuelle Zuteilung

### ISSUE THREAD

**Issue by philippjorek** [hkarl/svpb#105]
Fehlerermittlung von J.:
https://dev1.svpb.de/arbeitsplan/manuelleZuteilung/?aufgabengruppe=16&zuteilungen_ausreichend=UN&mitglied_ausgelastet=FRAM&filter=Filter+anwenden

Der gesamte Block „Manuelle Zuteilung“
 funktioniert nicht
![image](https://user-images.githubusercontent.com/18530580/151528431-4eb0c613-7922-49ba-89fb-db3169f45cf5.png)
![image](https://user-images.githubusercontent.com/18530580/151528547-8f64293f-4469-4163-8d60-5e1da14b4555.png)

**Comment by mdynia** [comment]
I am guessing the message "Exception Value: | **must be str, not bytes**" refers to the dist (attrs) param that is passed as 3rd parameter to arbeitsplan\tables.py [244]
> klass = type(name, (django_tables2.Table,), attrs)

{
    'kontakt': <arbeitsplan.tables.KontaktColumn object at 0x7f48b95336a0>, 
    'zugeteilt': <django_tables2.columns.base.Column object at 0x7f48b95337b8>, 
    'offen': <django_tables2.columns.base.Column object at 0x7f48b95337f0>, 
    b'SBF-See; Praktische Motorbootausbildung': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7f48b94e1128>, 
    b'SBF-Binnen; Praktische Motorbootausbildung': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7f48b94e15f8>, 
    b'SKS Seemeilentorn mit SKS-Prufung': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7f48b94e12e8>, 
    b'PA Hannover Vereinsgebaude aufschlieen Februar': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7f48b94e1e80>, 
    b'PA Hannover Vereinsgebaude offnen November': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7f48b94e1e48>, 
    b'PA Hannover Vereinsgebaude Januar': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7f48b94e1dd8>, 
    b'PA Hannover Vereinsgebaude aufschlieen Marz': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7f48b94e1b00>, 
    'Meta': <class 'arbeitsplan.tables.Meta'>
}

**Comment by mdynia** [comment]
Bytes literals are always prefixed with 'b' or 'B'; they produce an instance of the bytes type instead of the str type. They may only contain ASCII characters; bytes with a numeric value of 128 or greater must be expressed with escapes.

**Comment by mdynia** [comment]
ZuteilungsTable

**Comment by mdynia** [comment]
![image](https://user-images.githubusercontent.com/15523759/156051545-f36a75c5-e484-47b6-8a68-4f272670cb1b.png)
.encode function does this byte conversion

**Comment by mdynia** [comment]
@hkarl I have just fixed this by adding .decode() suffix here, and page gets displayed.
Can you confirm that this fix makes sence here?
