### ISSUE TITLE
Bisherige Funktion „Aufgabe löschen“ fehlt

### ISSUE THREAD

**Issue by philippjorek** [hkarl/svpb#109]
Fehlerermittlung von J.:
(aus Email vom 24.01.2022)

Bisherige Funktion
„Aufgabe löschen“ fehlt

![52](https://user-images.githubusercontent.com/18530580/151531621-35418fd9-f928-47cf-ae6c-128af27184e2.png)

**Comment by mdynia** [comment]
@philippjorek Was genau fehlt? Wo fehlt das? War es ein Button?

**Comment by philippjorek** [comment]
Hat sich erledigt. Hab eben mit Jochen gesprochen. Es funktioniert alles.

Es ging um den Button "Löschen". Dieser wird nur angezeigt, wenn der eingeloggte User = Verwantwortlicher im Formular ist
https://dev1.svpb.de/arbeitsplan/aufgabeEditieren/158/
