### ISSUE TITLE
Boot: Error "CSRF-Verifizierung fehlgeschlagen. Anfrage abgebrochen."

### ISSUE THREAD

**Issue by mdynia** [hkarl/svpb#113]
Error "CSRF-Verifizierung fehlgeschlagen. Anfrage abgebrochen." 
- beim Speichern von "Neue Schadensmeldungen"
- beim "Verbindlich reservieren"
-

**Comment by mdynia** [comment]
@philippjorek Will this issue disapear as soon as we move to HTPPS?
https://stackoverflow.com/questions/25954538/django-403-forbidden-csrf-verification-failed

**Comment by philippjorek** [comment]
I thought HTTPS is still working, because certificate was activated.
check visiting website https://dev1.svpb.de/
Or: how can i check HTTPS is working correctly?

**Comment by mdynia** [comment]
philippjorek ***@***.***> schrieb am Fr., 18. Feb. 2022,
17:16:

**Comment by mdynia** [comment]
**https**://dev1.svpb.de/boote/booking/boot/1/
![image](https://user-images.githubusercontent.com/15523759/155845879-d001711b-1ff0-466e-b85d-f07065ddb58b.png)

**Comment by mdynia** [comment]
Fixed by using "render" function and forwarding the request
> return render(request, 'boote/booking_boot.html',context)
