### ISSUE TITLE
Checkboxen fehlen -> Arbeitsplan: Zuteilung der Mitglieder (Priorität: sehr wichtig!)

### ISSUE THREAD

**Issue by philippjorek** [hkarl/svpb#120]
Nach Email von j.:
Vorstandsfunktion

Auf der Seite "Aufgaben an Mitglieder zuteilen" fehlen die Checkboxen in der Tabelle bzw, jene wurde deaktiviert
https://dev1.svpb.de/arbeitsplan/manuelleZuteilung/

Die Checkboxen wurden im Code auskommentiert
Zeile 1546
# print checkedboxes 
und ggf. Zeile 1648
# print "checkboxes: ", checkedboxes

Datei: svpb/arbeitsplan/views.py

Vermutung: Vllt gab es Migrations-Probleme seit dem Update auf dem neuen Server

Die Checkboxen werden dringend benötigt, um die Mitglieder zu den AUfgaben zuteilen zu können.
Es muss auch geprüft werden, ob die durch die Checkboxen verbundene Speicherfunktion für die Zuteilung der Mitglieder funktioniert.

**Comment by hkarl** [comment]
Die Zeilen 1546 und 1648 haben mit dem Editieren von Stundenplänen zu tun. Wir haben ja erstmal das Problem, das Zuteilen von Aufgaben nicht geht. Die relevante Klasse dazu ist 

```
 class ManuelleZuteilungView (isVorstandMixin, FilteredListView)
```
ab Zeile 1029

**Comment by hkarl** [comment]
Ok, das Problem grenzt sich ein auf die Frage, wie in Python3 bzw. aktueller Django-Version django_tables die Spalten-Header behandelt werden: als str oder als bytes. Im Queryset stehen die als bytes, aber in den Spaltenköpfen als str. Debug-Ausgabe aus tables.py, Funktion ZuteilungsTableFactory : 

```
XXX 2:  Online-Programme <class 'str'>
XXX 2:  Pflege homepage www svpb de <class 'str'>
XXX 2:  {'zugeteilt': <django_tables2.columns.base.Column object at 0x7fbc56b79860>, 'offen': <django_tables2.columns.base.Column object at 0x7fbc56b79898>, 'Online-Programme': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7fbc56b1f0b8>, 'Pflege homepage www svpb de': <arbeitsplan.tables.ValuedCheckBoxColumn object at 0x7fbc56b1f978>}
XXX TableFactory:  <django_tables2.tables.ZuteilungsTable object at 0x7fbc56b1f588>
XXX 2
odict_keys(['zugeteilt', 'offen', 'Online-Programme', 'Pflege homepage www svpb de', 'kontakt'])
[{'last_name': 'Karl', 'first_name': 'Holger', 'mitglied': <User: Holger Karl (Nr.: 00611)>, b'Online-Programme': (0, 'box_1_182', ' (1 / 2)'), b'Pflege homepage www svpb de': (-1, 'x'), 'zugeteilt': 0, 'offen': 12}, {'last_name': 'Bressler', 'first_name': 'Stephan', 'mitglied': <User: Stephan Bressler (Nr.: 00856)>, b'Online-Programme': (0, 'box_415_182', ' (2 / 1)<br><small>QUICKMELDUNG</small>'), b'Pflege homepage www svpb de': (-1, 'x'), 'zugeteilt': 0, 'offen': 12}, {'last_name': 'Milchers', 'first_name': 'Thomas', 'mitglied': <User: Thomas Milchers (Nr.: 01123)>, b'Online-Programme': (-1, 'x'), b'Pflege homepage www svpb de': (0, 'box_492_241', ' (2 / 1)<br><small>QUICKMELDUNG</small>'), 'zugeteilt': 0, 'offen': 12}]
```

und 'Online-Programme' ist leider nicht == b'Online-Programme'. Deswegen sind die Daten für die entsprechend Tabelle leer, und deswegen kommt da immer None raus :-( 

Totaler Mist. Keine Ahnung, wie man das nun elegant umgehen kann.

**Comment by hkarl** [comment]
Closed by 224b824064f07698cff75ea409f41c82c44435fd 

Das Problem war, dass die Tags für die Spaltenköpfe anders als die entsprechenden Dictionary-Einträge für die Daten unterschiedlich von Umlauten weg normalisiert wurden. Letztlich hat nur in views.py 2x decode gefehlt. Hoffe ich :-). Ich hoffe, das funktioniert so.

Was lernen wir daraus: Umlaute sind Mist :-( 👎 

Die ganze Code-Mechanik mit ```unicodedata.normalize``` muss kritisch durchgeschaut werden. Hier offenbaren sich mal wieder Unterschiede zwischen pyhton2 und python3, die sonst nicht so auffallen.
